name: ProjetoLeilao
services:
  rbas-db:
    image: postgres:11
    ports:
      - 5432
    environment:
      - POSTGRES_USER=pguser
      - POSTGRES_PASSWORD=pgpass
      - POSTGRES_DB=pgdb
    resources:
      cpu: 100m
      memory: 128Mi
  
  ProjetoLeilao:
    public: true
      image:okteto.dev/ProjetoLeilao:latest
    build: .
    replicas: 1
    command: bash -c "gunicorn ProjetoLeilao.wsgi --reload -b 0.0.0.0:8000"
    ports:
      - 8000
    resources:
      cpu: 100m
      memory: 128Mi